set encoding=utf-8
set guifont=Lucida_Console:h10
set number
set indentexpr=
autocmd FileType php,c set indentexpr= cindent
set nobackup
set nowritebackup
set noswapfile
set clipboard=unnamed
set shiftwidth=4
set cinoptions=>1s,^1s,:1s,=1s,C1s,(1s
set expandtab
set tabstop=4
set ignorecase
set ruler
colorscheme slate
syntax on
let g:skip_loading_mswin=1
set bs=2
set scrolloff=3
set showcmd
